AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '**/db/schema.rb'
    - '**/*.gemspec'
    - '**/vendor/**/*'
    - '**/bin/*'
    - '**/node_modules/**/*'

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Metrics/AbcSize:
  Max: 20
  Exclude:
    - '**/db/migrate/*'

Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'
    - '**/config/routes.rb'
    - '**/admin/*'
    - '**/config/environments/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - '**/db/migrate/*'

Style/Documentation:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: rails

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

